version: '3.7'

# postgresql service
services:
  postgresql:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init/create_second_db.sh:/docker-entrypoint-initdb.d/create_second_db.sh
    environment:
      - POSTGRES_USER=awokly_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev_awokly_db
